name: Release

on:
  push:
    branches:
      - master
      - feature

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: 'Get Previous tag'
        id: previoustag
        run: |
          LAST_VERSION=$(git describe --abbrev=0 --tags | sed 's/* //'  )
          echo "::set-output name=previous_tag::${FULL_VERSION}"
      
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.previous_tag }}

      - name: 'Publish Nightly Build - Master'
        id: publish_master
        if: github.ref == 'refs/heads/master'
        env:
          patch_version: ${{ steps.semvers.outputs.patch }}
        run: |
          echo "will publish patch version: ${patch_version}"

      - name: 'Publish Nightly Build - Feature'
        id: publish_feature
        if: github.ref == 'refs/heads/feature'
        env:
          minor_version: ${{ steps.semvers.outputs.minor }}
        run: |
          echo "will publish minor version: ${minor_version}"
