name: Release

on:
  push:
    branches:
      - master
      - feature

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: 'Publish Nightly Build - Master'
        id: publish_master
        if: github.ref == 'refs/heads/master'
        env:
          patch_version: ${{ steps.semvers.outputs.patch }}
        run: |
          echo "will publish patch version: ${patch_version}"

      - name: 'Publish Nightly Build - Feature'
        id: publish_feature
        if: github.ref == 'refs/heads/feature'
        env:
          minor_version: ${{ steps.semvers.outputs.minor }}
        run: |
          echo "will publish minor version: ${minor_version}"

