name: Release

on:
  push:
    branches:
      - master
      - feature

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - name: 'Get Previous tag'
        id: previoustag
        run: |
          git fetch --tags
          # This suppress an error occurred when the repository is a complete one.
          git fetch --prune --unshallow || true
          LAST_VERSION=$(git describe --abbrev=0 --tags)
          echo "Last Version: ${LAST_VERSION}"
          echo "::set-output name=previous_tag::${LAST_VERSION}"
      
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.previous_tag }}

      - name: 'Get Next Version'
        id: get_next_version
        run: |
          current_branch=$(git symbolic-ref --short -q HEAD)
          echo Current git branch is $current_branch
          if [ "$current_branch" == 'master' ] ; 
            then
              echo "::set-output name=next_version::${minor_version}"
            else
              echo "::set-output name=next_version::${patch_version}"
          fi
        env:
          patch_version: ${{ steps.semvers.outputs.patch }}
          minor_version: ${{ steps.semvers.outputs.minor }}

      - name: 'Publish Nightly Build - Master'
        id: publish_master
        if: github.ref == 'refs/heads/master'
        env:
          next_version: ${{ steps.get_next_version.outputs.next_version }}
        run: |
          echo "will publish next version: ${next_version}"

